<?php  

/**
 * @author 02.09.2018 Jeremiah Wodke <[<jeremiah.wodke@madwiremedia.com>]> 
 */

class Curl_Handler 
{

  protected $user_key;
  protected $url;
  protected $headers = [];

  /**
   * @return [set initial values for API request]
   */

  public function __construct($user_key, $username = null, $password = null)  {

    $this->user_key = $user_key;
    $this->username = $username;
    $this->password = $password;

  }

  public function set_content_type($type) {
    array_push($this->headers, 'Content-Type:application/' . $type);
  }

  public function set_auth($type) {
    if ($type == 'basic') {
      array_push($this->headers, 'Authorization: Basic '. base64_encode($this->username . ':' . $this->password));  
    }
  }

  public function request($url, $endpoint, $headers) {

    $ch = curl_init();

    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_POST, true);
    curl_setopt($ch, CURLOPT_POSTFIELDS, http_build_query($endpoint, '', '&'));
    curl_setopt($ch, CURLOPT_TIMEOUT, 30); //timeout after 30 seconds
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);

    $response = curl_exec ($ch);
    $status_code = curl_getinfo($ch, CURLINFO_HTTP_CODE); //get status code
    curl_close ($ch);

    return $response;

  }

}

class Org extends Curl_Handler 
{

  protected $username = 'grasons';
  protected $password = 'DgR7s253iSui3yFwmwcyGqH5tGNeJb';
  protected $base_url = 'https://estatesales.org/api/v2'; 
  protected $timezone = 'US/Central';
  protected $address;
  protected $city;
  protected $postal_code;
  protected $state_code;

  public function __construct($user_key, $address, $city, $postal_code, $state_code)  {

    $this->user_key    = $user_key;
    $this->address     = $address;
    $this->city        = $city;
    $this->postal_code = $postal_code;
    $this->state_code  = $state_code;
    $this->set_base_query();

  }

  private function set_base_query() {

    $this->base_query = [
          'user_key'    => $this->user_key,
          'address'     => $this->address,
          'city'        => $this->city,
          'state_code'  => $this->state_code,
          'postal_code' => $this->postal_code,
          'type'        => 'traditional'
        ];

  }

  /**
   * [for estatesales.org ONLY. Used to POST listings based from GPS coordinates to specify a specific ]
   * @param  
   * @return json response 
   * https://estatesales.org/api/v2/geocode/get
   */
  public function get_coordinates() {

    $geocode_url = $this->base_url . '/geocode/get';

    return json_decode($this->request($geocode_url, $this->base_query, $this->headers));

  }

  /**
   * [set the locations coordinates from the cURL response get_coordinates()]
   */
  private function set_coordinates() {

    $coords = $this->get_coordinates();

    $this->base_query['lat'] = $coords->location->lat;
    $this->base_query['lon'] = $coords->location->lon;

  }

  private function set_listing_id($id) {
    $this->listing_id = $id;
  }

  public function get_listing_id() {
    return $this->listing_id;
  }

  /**
   * @param Associative Array of Params
   * @return [type] [description]
   */
  private function build_endpoint($params) {

    $endpoint = $this->base_query;
    
    // Push values to endpoint storing base_query
    foreach ($params as $key => $value) {
      $endpoint[$key] = $value;
    }

    return $endpoint;

  }

  /**
   * [post listing to estate sales .org api.]
   * @param $[params_arr] [<an arr containing all params to add for initial content of post. Images will come next in sequence.>]
   * https://estatesales.org/api/v2/sale/set
   */
  public function post_listing($params_arr) {

    $url = $this->base_url . '/sale/set';

    $this->set_coordinates();

    $endpoint = $this->build_endpoint($params_arr);
    $listing = json_decode($this->request($url, $endpoint, $this->headers));

    $this->set_listing_id($listing->sale->id);
    $this->display_listing($listing->sale->id, true);
    
  }

  public function hide_listing()  {
    /**
     * @param  listing->id
     * @todo  I need to set up a database structure that stores listings and relates them to post IDs so upon deletion of a post I can delete a listing
     */
    $this->display_listing($listing->sale->id, false);
  }



  /**
   * [publish_listing on estatesales.org. You can remove a listing by firing another API request to the sale and setting publish=false]
   * @param  [int] $listing_id [id generated by post_listing() api response]
   * @return response whether listing was properly published or not
   * https://estatesales.org/api/v2/sale/publish/set
   */
  public function display_listing($listing_id, $show_hide) {

    $url = $this->base_url . '/sale/publish/set';

    $params = [

      'id' => $listing_id,
      'publish' => $show_hide

    ];

    $endpoint = $this->build_endpoint($params);
    $response = json_decode($this->request($url, $endpoint, $this->headers));

  }

  /**
   * [post an image to the estatesales.org account]
   * @return [respsone obj]
   */
  public function post_images($images_arr) {

    $url = $this->base_url . '/sale/photo/remote/add';

    if (count($images_arr) > 0) {

      foreach ($images_arr as $row => $image) {

        $params = [
          'id' => $this->listing_id,
          'url' => wp_get_attachment_url($image['field_5a69fa961c0b7'])
        ];
        
        $endpoint = $this->build_endpoint($params);
        $response = json_decode($this->request($url, $endpoint, $this->headers));

      }
      
    }

  }

  /**
   * return json formatted obj of date ACFs in proper format for API
   * @param  an array of dates and times
   * @return the formatted json dates obj
   */
  public function format_dates($dates_arr) {

    $formatted = [];

    foreach ($dates_arr as $row => $date) {

      // format raw format returned from uprocessed ACF
      $format_in = 'Ymd';
      $format_out = 'Y-m-d';
      $temp_date = DateTime::createFromFormat($format_in, $date['field_5a8334c3826bc']);
      $new_date = $temp_date->format( $format_out );

      if (!empty($date['field_5a833588826bf'])) {

        $formatted[$new_date] = [$date['field_5a83356e826be'], $date['field_5a833588826bf']];  

      } else {

        $formatted[$new_date] = [$date['field_5a83356e826be']];

      }

    }

    return json_encode($formatted);

  }

}


// Run the API Calls Upon Estate Sale Custom Post Type CREATION OR DELETION
add_action( 'transition_post_status', 'post_estate_sale_to_apis', 10, 3 );

function post_estate_sale_to_apis( $new_status, $old_status, $post ) { 

  if (($old_status == 'draft' || $old_status == 'auto-draft') && $new_status == 'publish' && $post->post_type == 'estatesales') {

    $fields   = $_POST['acf'];  
    $title    = get_the_title($post->ID);
    $address  = $fields['field_5a69f982b7d3a'];
    $account  = $fields['field_5a83313334dc9'];
    $city     = $fields['field_5a69f998b7d3b'];
    $state    = $fields['field_5a8332d3fb503'];
    $zipcode  = $fields['field_5a833310fb504'];
    $timezone = $fields['field_5a833d1c1c319'];
    $descr    = $fields['field_5a8330f0e668a'];
    $dates    = $fields['field_5a69f9e9b7d3c'];
    $images   = $fields['field_5a69fa731c0b6'];

    $org = new Org($account, $address, $city, $zipcode, $state);
    
    $params = [
      'descr' => $descr, 
      'title' => $title,
      'timezone' => $timezone, 
      'dates' => $org->format_dates($dates)
    ];

    $org->set_content_type('x-www-form-urlencoded');
    $org->set_auth('basic');
    $org->post_listing($params);

  }

}