<?php
    $user_role = get_userdata(get_current_user_id())->roles[0];  
    $user = Account::get($user_role);
?>


<style>
    #external-websites-form-wrapper,
    #external-websites-form input {
        width: 80%;
        max-width: 100%;
        margin: 40px auto;
        border-radius: 2px;
    }

    #external-websites-form {
        background: #eee;
    }

    #external-websites-form label,
    #external-websites-form input {
        font-size: 20px;
    }

    #external-websites-form input {
        height: 25px;
        margin: 5px 0 15px;
        height: 40px;
    }
</style>

<div id="external-websites-form-wrapper">
    <h1>External Web Configuration</h1>

    <p>
        Enter the ID's for the following external Estate Sales Websites if you have already set them up. Each field is <em>optional</em> but connects to a different web service that on Post submission via your <a href="<?= home_url(); ?>/wp-admin/edit.php?post_type=estatesales">Estate Sales content manager</a> <em>( located in the top left Sidebar )</em>. If a field below is left blank on Post submission content will NOT be published to that external website. This feature will streamline the large amounts of image content and estate sale information that you are currently adding to each of these websites manually. If you have any questions pertaining to this feature please contact your administrator.
    </p>

    <p><strong>Make sure you enter the <span style="color:red;">EXACT</span> ID for each external website or the software will be unable to publish your content to that external website.</strong></p>

    <hr>

    <form action="<?= esc_url( admin_url( 'admin-post.php' ) ); ?>" method="POST" id="external-websites-form">
        <input type="hidden" name="action" value="external_websites_form_response">
        <input type="hidden" name="user_role" value="<?= $user_role; ?>">
        <?php wp_nonce_field( 'external_websites_form_response', 'external_website_form_nonce' ); ?>
        
        <div>
            <label for="com" name="net">EstateSales.Net Company ID</label>
            <div>
                <p>Website: <a href="https://www.estatesales.net/">EstateSales.net</a></p>
                <p>The company ID for this account looks something similar to this: <strong>23126</strong>. You can view it next to your company name in your <a target="_blank" href="https://www.estatesales.net/account/org/settings/">account dashboard</a></p>
                <input type="text" name="net" value="<?= (isset($user['net'])) ? $user['net'] : '';  ?>">
            </div>
        </div>
        
        <div>
            <label for="org" name="org">EstateSales.Org Company ID</label>
            <div>
                <p>Website: <a href="https://estatesales.org/">EstateSales.org</a></p>
                <p>The company ID for this account looks something similar to this: <strong>5749-0950-0d1d-4c13-9ed8-6154</strong> will be lcoated at the bottom of your <a target="_blank" href="https://estatesales.org/account/settings">account settings</a></p>
                <input type="text" name="org" value="<?= (isset($user['org'])) ? $user['org'] : '';  ?>">
            </div>
        </div>
        
        <div>
            <label for="net" name="com">EstateSales.Com Company ID</label>
            <div>
                <p>Website: <a href="http://estatesale.com/">EstateSale.com</a></p>
                <p>The company ID for this account looks something similar to this: <strong>5829</strong>. You can view it next to your company name in your <a target="_blank" href="https://www.estatesale.com/companies/successful/">account dashboard</a></p>
                <input type="text" name="com" value="<?= (isset($user['com'])) ? $user['com'] : '';  ?>">
            </div>
        </div>

  <!--       <div>
            <label for="facebook" name="net_id">Facebook Page ID</label>
            <div>
                <p>Website: <a href="http://business.facebook.com/">Facebook</a></p>
                <input type="text" name="facebook" value="<? //(isset($user['facebook'])) ? $user['facebook'] : '';  ?>">
            </div>
        </div>

        <div>
            <label for="hootsuite" name="net_id">Hootsuite</label>
            <div>
                <p>This ID is dynamically generated by Hootsuite's external software. <strong>This is for reference ONLY.</strong></p>
                <input disabled type="text" name="hootsuite" value="<? //(isset($user['hootsuite'])) ? $user['hootsuite'] : '';  ?>">
            </div>
        </div>
         -->
        <div>
            <input type="submit" class="button button-primary button-large" value="Save">
        </div>
        
    </form>
</div>